spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

springdoc:
  api-docs:
    path: /admin/v3/api-docs

open-weather-api:
  host: api.openweathermap.org/data/2.5/weather
